version: "3.8"

# For local development, only database is running
#
# docker-compose up -d
# uvicorn app.main:app --reload
#

services:
  db:
    restart: always
    image: postgres:14.5
    container_name: db
    hostname: db
    volumes:
      - ${POSTGRES_HOME_DIR}/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DEFAULT_DATABASE_DB}
      - POSTGRES_USER=${DEFAULT_DATABASE_USER}
      - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "${DEFAULT_DATABASE_PORT}:5432"
    networks:
      - backend
  
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    hostname: api
    env_file:
      - .env
    tty: true
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - db



  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: redis
    hostname: redis
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'